name: TOTO Results Auto-Update

on:
  schedule:
    # Run every day at 7:30 PM and 10:30 PM SGT (11:30 AM and 2:30 PM UTC)
    - cron: '30 11,14 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        npm ci || npm install
        
    - name: Fetch latest TOTO results
      run: |
        node toto-fetcher.js
      
    - name: Check for changes
      id: verify-changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "No changes to commit"
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push if there are changes
      if: steps.verify-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Extract winning numbers for commit message
        NUMBERS=$(tail -n 1 totoResult.csv)
        
        git add totoResult.csv
        git commit -m "🎯 Update TOTO results: Latest numbers $NUMBERS"
        git push
